### ISSUE TITLE
Graphics not properly loaded & error in checking the winner

### ISSUE THREAD

**Issue by hearot** [loernzo/PyTacToe#1]
I've been trying PyTacToe for a while and noticed some errors.

```
**Welcome to PyTacToe!**
    x 1     2     3
y
1

2

3


Crosses (format: x, y): 1, 1
    x 1     2     3
y
1x

2

3


Circles (format: x, y): 2, 1
    x 1     2     3
y
1xo

2

3


Crosses (format: x, y): 3, 3
    x 1     2     3
y
1xo

2

3x


Circles (format: x, y): 2, 2
    x 1     2     3
y
1xo

2o

3x


Crosses (format: x, y): 3, 1
    x 1     2     3
y
1xox

2o

3x


Circles (format: x, y): 2, 3
    x 1     2     3
y
1xox

2o

3ox
```

In fact, you can never win. I let the circles win on purpose by taking all the `(2, y)` coordinates and, indeed, they did not win. Beyond that, the game table is not correctly printed.

I noticed that on [line 112 of pytactoe.py](https://github.com/loernzo/PyTacToe/blob/master/pytactoe/pytactoe.py#L112) the program shuts down without checking if the circles actually won.

**Comment by loernzo** [comment]
Solved, it was caused by me and my inabilty with Git which had completely broken the code
