### ISSUE TITLE
Missing shebang

### ISSUE THREAD

**Issue by hearot** [loernzo/PyTacToe#3]
I'd suggest to add a [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) to [pytactoe.py](https://github.com/loernzo/PyTacToe/blob/master/pytactoe/pytactoe.py).

```
#!/usr/bin/python
# -*- coding: utf-8 -*-
```

**Comment by loernzo** [comment]
Thanks! Just added it.
